name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun i --frozen-lockfile
      - run: bun run lint --fix

      - uses: autofix-ci/action@v1
        if: always()
        with:
          commit-message: 'style: autofix'
